config/routes.rb
BeingMindful::Application.routes.draw do
  
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :users do 
    member do 
      get :following, :followers
    end
  end # ie. /users/1/followers(ing)

  root 'static_pages#index'

  resources :sessions, only: [:new, :create, :destroy] 
  resources :posts, only: [:create, :destroy, :index, :show]
  resources :relationships, only: [:create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/search',  to: 'users#search',     via: 'get'

  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class='error'>
    <div class='alert alert-error'>
      The form contains <%= pluralize(object.errors.count, "error") %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>

  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">

    <%= link_to gravatar_for(feed_item.user), feed_item.user %>

    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>

    <span class="content well">
      <%= feed_item.content.html_safe %><br />
      <div class="image center">
        <%= image_tag feed_item.image %>
      </div>

    <div class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </div>
    
      <div class="delete">
        <% if current_user?(feed_item.user) %>
        <%= link_to "delete", feed_item, method: :delete,
              data: { confirm: "Delete this post?" },
              title: feed_item.content %>
      </div>
    </span>    

    <% end %>

</li>

app/views/shared/_post_form.html.erb
<%= form_for(@post, html: {:multipart => true}) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <%= f.bootsy_area :content, rows: 6, placeholder: "Compose new post..." %><br />
<!--     <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>  --> 
    
    <%= f.submit "Post", class: "btn-sm btn-primary", id: "button" %>

<% end %>

app/views/shared/_search.html.erb
<%= form_tag(users_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-danger", id: 'button' %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_feed.html.erb
<% if current_user?(@user) %>
  <ol class="posts">
    <%= render partial: 'shared/feed_item', collection: @user %>
  </ol>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.posts.count, "post") %>
</span>