config/routes.rb
BeingMindful::Application.routes.draw do
  
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :users do 
    member do 
      get :following, :followers
    end
  end # ie. /users/1/followers(ing)

  root 'static_pages#index'

  resources :sessions, only: [:new, :create, :destroy] 
  resources :posts, only: [:create, :destroy, :index, :show]
  resources :relationships, only: [:create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/search',  to: 'users#search',     via: 'get'

  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/layouts/_footer.html.erb
<div class="container">
<footer class="footer">
  <small>
    Created by: <%= link_to "cbstodd", "https://github.com/cbstodd", target: "_blank" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "beingmindful.com", root_path, class: "navbar-brand", id: "logo" %>
    </div>
      <nav class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>

        <% if signed_in? %>

          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="header_links">
            Account<span class="caret"></span></a>
          <ul class="dropdown-menu " role="menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
        </li>

        <% else %>

         <li><%= link_to "Sign in", signin_path, id: "header_links" %></li>

        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  
    <%= render 'layouts/footer' %>
    
  </div>

</body>
</html>